size = [800, 400]
bg_image = "assets/images/arch-linux.png"
terminal_cmd = "ghostty --wait-after-command=true -e bash -c \"{CMD}\""
actions = {
    suspend = "systemctl suspend",
    shutdown = "shutdown now",
}

[visual.style]
widget = {
    padding = [20, 20, 20, 20],
    background = "#211e20ff",
    border = {
        color = "#e9efecff",
        width = 2,
        radius = [0, 0, 0, 0],
    },
}

text = {
    color = "#555568ff",
}
"#selected" = {
    color = "#e9efecff",
}

input = {
    background = "#0", # Transparent
    color = "#e9efecff",
    highlight = "#a0a08bff",
}

scroll = {
    padding = [0, 10, 0, 10],
}
"scroll.rail.scroller" = {
    background = "#555568ff",
}
"scroll.dragged.rail.scroller" = {
    background = "#a0a08bff",
}

image = {
    height = 250,
    opacity = 0.2,
}
