size = [800, 400]

style.widget.padding = [20, 20, 20, 20]
style.widget.background = "#F8F9FAFF"
style.widget.color = "#222222FF"

[style.widget.border]
color = [0, 0, 0, 0] # Transparent
width = 1
radius = [20, 20, 20, 20]
