size = [500, 500]
bg_image = "assets/images/arch-linux.png"
terminal_cmd = "ghostty --wait-after-command=true -e bash -c \"{CMD}\""
actions = {
    suspend = "systemctl suspend",
    shutdown = "shutdown now",
}

[visual.style]
widget = {
    padding = [80, 50, 80, 50],
    background = "#211e20ff",
    border = {
        color = "#e9efecff",
        width = 2,
        radius = [1000, 1000, 1000, 1000],
    },
    align_x = "Center",
}

text = {
    color = "#555568ff",
    line_height = 40,
}
"#selected" = {
    color = "#e9efecff",
    text_size = 19,
}

input = {
    background = "#0", # Transparent
    color = "#e9efecff",
    highlight = "#a0a08bff",
    align_x = "Center",
}

scroll = {
    padding = [0, 10, 0, 10],
    background = "#00000000",
}
# "scroll.rail.scroller" = {
#     background = "#555568ff",
# }
# "scroll.dragged.rail.scroller" = {
#     background = "#a0a08bff",
# }

image = {
    height = 250,
    opacity = 0.2,
}
