[package]
name = "nexus-launcher"
version = "0.1.0"
edition = "2024"
authors.workspace = true

[dependencies]
calc_this = { path = "../calc_this" }
clap.workspace = true
fuzzy-matcher.workspace = true
iced = { workspace = true, features = ["tokio"] }
kool = { path = "../kool" }
nexusctl = { path = "../nexusctl" }
serde.workspace = true
tokio = { workspace = true, features = ["time"] }
toml.workspace = true
xdg.workspace = true
